#--------------------------------------------------------------
#Memo: 取得する値は進む距離と進行速度
#Memo: サービスに対して要求があったら resultとdistance,velocity
#--------------------------------------------------------------

# request
#型 フィールド名
float32 distance
float32 velocity

---
#response
bool result
